let size = 30;

export default {
    name:"Enemy",
    components:[
        {
            type:"RectangleComponent",
            values:[
                {
                    key:"width",
                    value:size
                },
                {
                    key:"height",
                    value:size
                },
                {
                    key:"fill",
                    value:"black"
                },
                {
                    key:"stroke",
                    value:"black"
                }
            ]
        },
        {
            type:"EnemyBehavior",
            values:[
                {
                    key:"isShooter",
                    value:false
                }
            ]
        },
        {
            type:"AABBCollider",
            values:[
                {
                    key:"width",
                    value:size
                },
                {
                    key:"height",
                    value:size
                },
                {
                    key:"layer",
                    value: 99
                }
            ]
        }
    ]
}